language: android
jdk: oraclejdk8

sudo: false
env:
  global:
  - ANDROID_API_LEVEL=25
  - ANDROID_BUILD_TOOLS_VERSION=25.0.2
android:
  components:
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_API_LEVEL
  - extra-google-google_play_services
  - extra-android-support
  - sys-img-armeabi-v7a-google_apis-21

deploy:
  provider: releases
  api_key:
    secure: 3a29c4b1f509760321dda7575764953d150fcfd8
  file: app/WM*.apk
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: javadghane/WikiMiki
